// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAma5p44g5nTNWyLSzasJWtmoBpszFwms',
    appId: '1:1074391323036:web:3546b783bdca49ed717859',
    messagingSenderId: '1074391323036',
    projectId: 'quick-mart-ecommerce-app',
    authDomain: 'quick-mart-ecommerce-app.firebaseapp.com',
    storageBucket: 'quick-mart-ecommerce-app.appspot.com',
    measurementId: 'G-MQV8LXJE24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWoDsP-pcxXOe1exGvJdBR1nadhI-VxRI',
    appId: '1:1074391323036:android:c2d099d548935fbf717859',
    messagingSenderId: '1074391323036',
    projectId: 'quick-mart-ecommerce-app',
    storageBucket: 'quick-mart-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJvH_8TYM-GW3T1ZoaRlIVTGXsQ-PZtg0',
    appId: '1:1074391323036:ios:a7a747bb2897afe1717859',
    messagingSenderId: '1074391323036',
    projectId: 'quick-mart-ecommerce-app',
    storageBucket: 'quick-mart-ecommerce-app.appspot.com',
    androidClientId: '1074391323036-8vbpp81jikv9ngs42hdrnjkj1rdrlnl7.apps.googleusercontent.com',
    iosClientId: '1074391323036-72lhhpcojop10no9pakkgs7ffvo0hjac.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJvH_8TYM-GW3T1ZoaRlIVTGXsQ-PZtg0',
    appId: '1:1074391323036:ios:a7a747bb2897afe1717859',
    messagingSenderId: '1074391323036',
    projectId: 'quick-mart-ecommerce-app',
    storageBucket: 'quick-mart-ecommerce-app.appspot.com',
    androidClientId: '1074391323036-8vbpp81jikv9ngs42hdrnjkj1rdrlnl7.apps.googleusercontent.com',
    iosClientId: '1074391323036-72lhhpcojop10no9pakkgs7ffvo0hjac.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAma5p44g5nTNWyLSzasJWtmoBpszFwms',
    appId: '1:1074391323036:web:6e5cb35d0b2debec717859',
    messagingSenderId: '1074391323036',
    projectId: 'quick-mart-ecommerce-app',
    authDomain: 'quick-mart-ecommerce-app.firebaseapp.com',
    storageBucket: 'quick-mart-ecommerce-app.appspot.com',
    measurementId: 'G-580HB6RHPW',
  );

}